### ISSUE TITLE
native system file browser not working. only ES File explorer working,

### ISSUE THREAD

**Issue by poppypundit** [SpEcHiDe/WhatsAppTransmitter#3] opened 2016-06-15 16:17 UTC
Its greyed out when asked to choose file. Not sure if it was meant to be like that,  as is.....

**Comment by SpEcHiDe** [comment] 2016-06-15 17:35
Are you using Android 4.4.4 ? 
If NO: Could you please give more details about the issue?

**Comment by poppypundit** [comment] 2016-06-15 22:13
I'm on CM13 Marshmallow, x86 architecture. I could see "message to show on what's app". After filling that in, when I click choose file, it opens the default system file explorer. When I browser to pick the file I need, its greyed out. ( I could not select it; but can only see it ) I can email/telegram you screen shots.

**Comment by poppypundit** [comment] 2016-06-15 22:17
I tried an apk file first. As it didn't work, I tried documents and then later pictures. I wasn't able to select either of them.

**Comment by SpEcHiDe** [comment] 2016-06-22 02:32
@poppypundit I think the problem is with Android 6 permissions. 
As I am too lazy to implement the Notification asking thing, please give the application the permission to access the files on storage device.

**Comment by poppypundit** [comment] 2016-06-22 06:49
I have given it "Storage permission" The problem still exists. I've managed to " select " an apk file using a third party file browser vs the native system file browser. But the app crashes instantly.

**Comment by erdmark** [comment] 2017-01-17 16:13
On Android 4.4.2 app crashes after selecting a file

**Comment by SpEcHiDe** [comment] 2017-01-18 04:15
@erdmark Unfortunately, I deleted the server where the file was supposed to be saved. 

A new version is in progress which would not need any third party servers! Please wait..

**Comment by erdmark** [comment] 2017-03-29 15:08
Thanks for your work but I don't have Whatsapp anymore. I think working on open projects like Conversations is better than improving a big company's apps.

**Comment by SpEcHiDe** [comment] 2017-03-29 16:55
@erdmark If you see the last commit it's 8 months old. I stopped working on this project because of the attached screenshot. 
![screenshot from 2017-03-29 22-25-11](https://cloud.githubusercontent.com/assets/6317196/24466470/9c24f118-14ce-11e7-8f37-4274a03b7549.png)

So, closing this issue.

**Closed as completed by SpEcHiDe** 2017-03-29 16:55 UTC
